[build]
  command = "npm run build:protected"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

# Production context
[context.production]
  command = "npm run build:protected"

# Deploy Preview context
[context.deploy-preview]
  command = "npm run build:protected"

# Branch Deploy context
[context.branch-deploy]
  command = "npm run build:protected"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.netlify.app https://api.fyra.app;"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), interest-cohort=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache Control
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Block access to sensitive files
[[headers]]
  for = "/.env"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Content-Type = "text/plain"
    Status = "404"

[[headers]]
  for = "/package.json"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Content-Type = "text/plain"
    Status = "404"
